version: "3"

services:
    redis:
        container_name: redis
        image: redis:7.2.3-alpine
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        networks:
            project_net:
                ipv4_address: ${REDIS_HOST}

    pg:
        container_name: pg
        image: postgres:17.5-bookworm
        ports:
            - "${PG_PORT}:${PG_PORT}"
        shm_size: ${PG_SHM_SIZE}mb
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB_NAME}
        networks:
            project_net:
                ipv4_address: ${PG_HOST}

networks:
    project_net:
        name: ${PROJECT_NAME}_net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_NETWORK}
