services:
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
            PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
        ports:
            - "${PGADMIN_PORT}:${PGADMIN_PORT}"
        networks:
            project_net:
                ipv4_address: ${PGADMIN_HOST}
    springboot:
        container_name: springboot
        build: context:../BE/SpringBoot
        dockerfile: Dockerfile
        evniroment:
            - PG_HOST=${PG_HOST}
            - PG_DB_NAME=${PG_DB_NAME}
            # TODO: 這邊要抽到 env，username: postgre為測試用
            - PG_USER=postgre
            - DB_PASSWORD=${PG_PASSWORD}
        volume:
            - ../BE/SpringBoot

networks:
    project_net:
        name: ${PROJECT_NAME}_net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_NETWORK}
